DATA:
    BATCH_SIZE: 2  # per GPU [total bs is set to 8 or 16]
    BATCH_SIZE_VAL: 1  # per GPU
    DATASET: 'PascalContext' # dataset name
    DATA_PATH: '/home/ssd3/wutianyi/datasets/pascal_context'
    CROP_SIZE: (480,480)
    NUM_CLASSES: 60
MODEL:
    NAME: 'SETR_MLA'
    ENCODER:
        TYPE: 'ViT_MLA'
        OUT_INDICES: [5, 11, 17, 23] # Base: [2, 5, 8, 11]; Large: [5, 11, 17, 23] 
    DECODER_TYPE: 'VIT_MLAHead'
    PRETRAINED: './pretrain_models/backbones/vit_large_patch16_224.pdparams'
    TRANS:
        PATCH_SIZE: 16
        HIDDEN_SIZE: 1024 # 768(Base), 1024(Large), 1280(Huge)
        MLP_RATIO: 4     # same as mlp_ratio = 4.0
        NUM_HEADS: 16    # 12(Base), 16(Large), 16(Huge)
        NUM_LAYERS: 24   # 12(Base), 24(Large), 32(Huge)
        QKV_BIAS: True
    MLA:
        MLA_CHANNELS: 256
        MLAHEAD_CHANNELS: 128
        MLAHEAD_ALIGN_CORNERS: False
    AUX:
        AUXIHEAD: True
        AUXHEAD_ALIGN_CORNERS: False
TRAIN:
    BASE_LR: 0.001
    END_LR: 1e-4
    DECODER_LR_COEF: 10.0
    ITERS: 80000
    POWER: 0.9
    DECAY_STEPS: 80000
    LR_SCHEDULER:
        NAME: 'PolynomialDecay'
    OPTIMIZER:
        GRAD_CLIP: 1.0
        WEIGHT_DECAY: 0.0
        NAME: 'SGD'
        MOMENTUM: 0.9
VAL:
    MULTI_SCALES_VAL: False
    SCALE_RATIOS: [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
    IMAGE_BASE_SIZE: 520
    CROP_SIZE: [480,480]
    STRIDE_SIZE: [320,320] 

SAVE_DIR: "./output/SETR_MLA_Large_480x480_80k_pascal_context_bs_8"

        

