DATA:
    BATCH_SIZE: 2  # per GPU [total bs is set to 8 or 16]
    BATCH_SIZE_VAL: 1  # per GPU
    DATASET: 'Vaihingen' # dataset name
    DATA_PATH: 'G:\Datasets\Vaihingen'
    CROP_SIZE: (256,256)  # input_size (training)
    NUM_CLASSES: 6
MODEL:
    NAME: 'Segmenter'
    ENCODER:
        TYPE: 'ViT'
        OUT_INDICES: [11] 
    PRETRAINED: 'pretrain_models\backbones\vit_base_patch16_224.pdparams'
    DECODER_TYPE: 'Linear'
    SEGMENTER:
      NUM_LAYERS: 2
    NUM_CLASSES: 6
    TRANS:
        PATCH_SIZE: 16
        HIDDEN_SIZE: 768 # 192(tiny), 384(small) 768(Base), 1024(Large), 1280(Huge)
        MLP_RATIO: 4     # same as mlp_ratio = 4.0
        NUM_HEADS: 12    # 3(tiny), 6(small), 12(Base), 16(Large), 16(Huge)
        NUM_LAYERS: 12   # 12(tiny), 12(small), 12(Base), 24(Large), 32(Huge)
        QKV_BIAS: True
        KEEP_CLS_TOKEN: True
TRAIN:
    BASE_LR: 0.00006
    END_LR: 0.0
    DECODER_LR_COEF: 10.0
    ITERS: 20000
    POWER: 1.0
    DECAY_STEPS: 20000
    LR_SCHEDULER:
        NAME: 'PolynomialDecay'
    OPTIMIZER:
        GRAD_CLIP: 1.0
        WEIGHT_DECAY: 0.01
        NAME: 'AdamW'
        MOMENTUM: 0.9
VAL:
    MULTI_SCALES_VAL: False
    IMAGE_BASE_SIZE: [2048, 1536]
    CROP_SIZE: [256, 256]
    STRIDE_SIZE: [171, 171]
    MEAN: [123.675, 116.28, 103.53]
    STD: [58.395, 57.12, 57.375]
SAVE_DIR: "./output/segmenter_base_linear_256x256_20k_vaihingen_bs_16"

        

