from .vit_mla_head import VIT_MLAHead
from .vit_mla_auxi_head import VIT_MLA_AUXIHead
from .vit_up_head import VisionTransformerUpHead
from .uper_head import UperHead
from .fcn_head import FCNHead
from .dpt_head import DPTHead
from .segmentor_head import MaskTransformer
from .segmentor_head import LinearDecoder
from .trans2seg_head import *
