DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: LINEARPROBE
    NAME: vit_huge_patch14_224
    GLOBAL_POOL: False
    PATCH_SIZE: 14
    MLP_RATIO: 4.0
    QKV_BIAS: true
    ENCODER:
        EMBED_DIM: 1280
        DEPTH: 32
        NUM_HEADS: 16
TRAIN:
    NUM_EPOCHS: 90
    WARMUP_EPOCHS: 10
    WEIGHT_DECAY: 0.0
    BASE_LR: 0.1
    LINEAR_SCALED_LR: 256
    END_LR: 0.0
    ACCUM_ITER: 1
    OPTIMIZER:
        NAME: 'LARS'
