DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: FINETUNE
    NAME: vit_large_patch16_224
    DROPPATH: 0.2 # same as MAE official readme
    GLOBAL_POOL: True
    PATCH_SIZE: 16
    MLP_RATIO: 4.0
    QKV_BIAS: true
    ENCODER:
        EMBED_DIM: 1024
        DEPTH: 24
        NUM_HEADS: 16
TRAIN:
    NUM_EPOCHS: 50
    WARMUP_EPOCHS: 5
    WEIGHT_DECAY: 0.05
    BASE_LR: 1e-3 # absolute_lr = base_lr * total_batch_size / 256
    LINEAR_SCALED_LR: 256
    END_LR: 1e-6
    ACCUM_ITER: 1
    OPTIMIZER:
        NAME: 'AdamWDL'
        BETAS: (0.9, 0.999)
    LAYER_DECAY: 0.75  # same as MAE official readme
    SMOOTHING: 0.1
    RAND_AUGMENT: True
    RAND_AUGMENT_LAYERS: 2
    RAND_AUGMENT_MAGNITUDE: 9
    MIXUP_ALPHA: 0.8
    MIXUP_PROB: 1.0
    MIXUP_SWITCH_PROB: 0.5
    MIXUP_MODE: 'batch'
    CUTMIX_ALPHA: 1.0
    CUTMIX_MINMAX: None
    RANDOM_ERASE_PROB: 0.25
    RANDOM_ERASE_MODE: 'pixel'
    RANDOM_ERASE_COUNT: 1
    RANDOM_ERASE_SPLIT: False

VALIDATE_FREQ: 1
SAVE_FREQ: 10
REPORT_FREQ: 100

