DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 1.0
    
MODEL:
    TYPE: cait
    NAME: cait_s24_224
    TRANS:
        PATCH_SIZE: 16
        EMBED_DIM: 384
        DEPTH: 24
        NUM_HEADS: 8
        INIT_VALUES: 1e-5
        DEPTH_TOKEN_ONLY: 2
