DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: PRETRAIN
    NAME: vit_large_patch16_224
    DROPPATH: 0.0
    TRANS:
        PATCH_SIZE: 16
        MLP_RATIO: 4.0
        QKV_BIAS: true
        MASK_RATIO: 0.75
        NORM_PIX_LOSS: True
        ENCODER:
            EMBED_DIM: 1024
            DEPTH: 24
            NUM_HEADS: 16
        DECODER:
            EMBED_DIM: 512
            DEPTH: 8
            NUM_HEADS: 16
TRAIN:
    NUM_EPOCHS: 800
    WARMUP_EPOCHS: 40
    WEIGHT_DECAY: 0.05
    BASE_LR: 1.5e-4
    WARMUP_START_LR: 1e-7
    LINEAR_SCALED_LR: 256
    GRAD_CLIP: None
    ACCUM_ITER: 1
    OPTIMIZER:
        NAME: 'AdamW'
        BETAS: (0.9, 0.95)
