DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: FINETUNE
    NAME: vit_base_patch16_224
    DROPPATH: 0.1
    GLOBAL_POOL: True
    TRANS:
        PATCH_SIZE: 16
        MLP_RATIO: 4.0
        QKV_BIAS: true
        ENCODER:
            EMBED_DIM: 768
            DEPTH: 12
            NUM_HEADS: 12
TRAIN:
    ACCUM_ITER: 4 # set batch size to 32
    NUM_EPOCHS: 100 # same as MAE official readme
    WARMUP_EPOCHS: 5
    WEIGHT_DECAY: 0.05
    BASE_LR: 5e-4
    LINEAR_SCALED_LR: 256
    END_LR: 1e-6
    OPTIMIZER:
        NAME: 'AdamWDL'
        BETAS: (0.9, 0.999)
    LAYER_DECAY: 0.65
    SMOOTHING: 0.1
    RAND_AUGMENT: True
    RAND_AUGMENT_LAYERS: 2
    RAND_AUGMENT_MAGNITUDE: 9
    MIXUP_ALPHA: 0.8
    MIXUP_PROB: 1.0
    MIXUP_SWITCH_PROB: 0.5
    MIXUP_MODE: 'batch'
    CUTMIX_ALPHA: 1.0
    CUTMIX_MINMAX: None
    RANDOM_ERASE_PROB: 0.25
    RANDOM_ERASE_MODE: 'pixel'
    RANDOM_ERASE_COUNT: 1
    RANDOM_ERASE_SPLIT: False

VALIDATE_FREQ: 1
SAVE_FREQ: 1
REPORT_FREQ: 20

