DATA:
    IMAGE_SIZE: 384
    CROP_PCT: 1.0
MODEL:
    TYPE: volo
    NAME: volo_d2_384
    TRANS:
        LAYERS: [6, 4, 10, 4]
        EMBED_DIMS: [256, 512, 512, 512]
        NUM_HEADS: [8, 16, 16, 16]
        MLP_RATIOS: [3, 3, 3, 3]
        DOWNSAMPLES: [True, False, False, False]
        OUTLOOK_ATTENTION: [True, False, False, False]
    STEM_HIDDEN_DIM: 64
