DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 1.0
MODEL:
    TYPE: volo
    NAME: volo_d1_224
    TRANS:
        LAYERS: [4, 4, 8, 2]
        EMBED_DIMS: [192, 384, 384, 384]
        NUM_HEADS: [6, 12, 12, 12]
        MLP_RATIOS: [3, 3, 3, 3]
        DOWNSAMPLES: [True, False, False, False]
        OUTLOOK_ATTENTION: [True, False, False, False]
    STEM_HIDDEN_DIM: 64
