DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 1.0
MODEL:
    TYPE: volo
    NAME: volo_d4_224
    TRANS:
        LAYERS: [8, 8, 16, 4]
        EMBED_DIMS: [384, 768, 768, 768]
        NUM_HEADS: [12, 16, 16, 16]
        MLP_RATIOS: [3, 3, 3, 3]
        DOWNSAMPLES: [True, False, False, False]
        OUTLOOK_ATTENTION: [True, False, False, False]
    STEM_HIDDEN_DIM: 64
