DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.9
MODEL:
    TYPE: poolformer
    NAME: poolformer_s36
    TRANS:
        LAYERS: [6, 6, 18, 6]
        EMBED_DIMS: [64, 128, 320, 512]
        LAYER_SCALE_INIT_VALUE: 1e-6

