DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.90
MODEL:
    TYPE: swin
    NAME: swin_small_patch4_window7_224
    DROP_PATH: 0.3
    TRANS:
        EMBED_DIM: 96
        STAGE_DEPTHS: [2, 2, 18, 2]
        NUM_HEADS: [3, 6, 12, 24]
        WINDOW_SIZE: 7
        PATCH_SIZE: 4

