DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.9
MODEL:
    TYPE: MobileFormer
    NAME: MobileFormer_294M
    DROPPATH: 0.1
    DROPOUT: 0.1
    MLP_DROPOUT: 0.1
    ATTENTION_DROPOUT: 0.1
    MF:
        IN_CHANNELS: 3
        TOKENS: [6, 192]
        NUM_HEAD: 8
        MLP_RATIO: 2.0
        ALPHA: 1.0
        QKV_BIAS: True
        POINTWISECONV_GROUPS: 1
        STEM:
            OUT_CHANNELS: 16
            KERNELS: 3
            STRIEDS: 2
            PADDINGS: 1
        LITE_BNECK:
            IN_CHANNEL: 16
            HIDDEN_CHANNEL: 32
            OUT_CHANNEL: 16
            KERNEL: 3
            STRIED: 1
            PADDING: 1
        BLOCK:
            IN_CHANNELS: [16, 24, 24, 48, 48, 96, 96, 128, 128, 192, 192]
            HIDDEN_CHANNELS: [96, 96, 144, 192, 288, 384, 576, 768, 768, 1152, 1152]
            OUT_CHANNELS: [24, 24, 48, 48, 96, 96, 128, 128, 192, 192, 192]
            KERNELS: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
            STRIEDS: [2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1]
            PADDINGS: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
        CHANNEL_CONV:
            IN_CHANNEL: 192
            OUT_CHANNEL: 1152
        HEAD:
            IN_CHANNEL: 1152
            HIDDEN_FEATURE: 1920
        DYRELU:
            USE_DYRELU: True
            REDUCE: 3.8
            DYRELU_K: 2
            COEFS: [1.0, 0.5]
            CONSTS: [1.0, 0.0]