DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: PVTv2
    NAME: pvtv2_b2_linear
    TRANS:
        PATCH_SIZE: 4
        EMBED_DIMS: [64, 128, 320, 512]
        STAGE_DEPTHS: [3, 4, 6, 3]
        NUM_HEADS: [1, 2, 5, 8]
        MLP_RATIO: [8, 8, 4, 4]
        SR_RATIO: [8, 4, 2, 1]
        LINEAR: True
        QKV_BIAS: True
    DROP_PATH: 0.0 #0.1
FPN:
    IN_CHANNELS: [64, 128, 320, 512]
TRAIN:
    GRAD_CLIP: None

