DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 1.0
MODEL:
    TYPE: xcit
    NAME: xcit_tiny_24_p16_224
    TRANS:
        PATCH_SIZE: 16
        EMBED_DIM: 192
        DEPTH: 24
        NUM_HEADS: 4
        ETA: 1e-5
        TOKENS_NORM: True

