DATA:
    DATASET: "ADE20K"
    BATCH_SIZE: 4
    BATCH_SIZE_VAL: 1
    DATA_PATH: "/home/ade/ADEChallengeData2016"
    CROP_SIZE: (512, 512)
    NUM_CLASSES: 150
TRAIN:
    BASE_LR: 0.0001
    END_LR: 0.0
    ITERS: 320000
    IGNORE_INDEX: 255
    LOSS: "MixSoftmaxCrossEntropyLoss"
    LR_SCHEDULER:
        NAME: "WarmupPolyLR"
    OPTIMIZER:
        NAME: 'ADAM'
        WEIGHT_DECAY: 1e-4
VAL:
    MULTI_SCALES_VAL: False
    IMAGE_BASE_SIZE: 512
    CROP_SIZE: [512, 512]
MODEL:
    NAME: "Trans2Seg"
    ENCODER:
        TYPE: "resnet50c"
    TRANS2SEG:
        EMBED_DIM: 256
        DEPTH: 4
        NUM_HEADS: 8
        MLP_RATIO: 3.
        HID_DIM: 64
    AUX:
        AUXIHEAD: False
        AUXHEAD_ALIGN_CORNERS: False
    PRETRAINED: "/home/aistudio/resnet50c.pdparams"
SAVE_DIR: "./output/trans10kv2/Trans2Seg_medium_512x512_16k_trans10kv2_bs_16"
