DATA:
    IMAGE_SIZE: 384
    CROP_PCT: 1.0
MODEL:
    TYPE: BEiT
    NAME: beit_base_patch16_384
    TRANS:
        PATCH_SIZE: 16
        EMBED_DIM: 768
        DEPTH: 12
        NUM_HEADS: 12
        MLP_RATIO: 4
        USE_ABS_POS_EMB: False
        USE_REL_POS_BIAS: True
        INIT_VALUES: 0.1