DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 1.0
MODEL:
    TYPE: CrossViT
    NAME: crossvit_vit_18_dagger_224
    TRANS:
        IMG_SIZE: [408, 384]
        PATCH_SIZE: [12, 16]
        EMBED_DIM: [224, 448]
        DEPTH: [[1, 6, 0], [1, 6, 0], [1, 6, 0]]
        NUM_HEADS: [7, 7]
        MLP_RATIO: [3, 3, 1]
        QKV_BIAS: True
        MULTI_CONV: True